hotwax/job-manager

- changelogs/unreleased/-21aqct8.yml
- src/views/Inventory.vue
- src/views/Login.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
- src/views/Settings.vue
> Removed fullscreen=true from ion-content of all pages(#21aqct8)

- src/components/BatchModal.vue
> Added slot icon-only to ion-icon in ion-button(#238uwuv)

- changelogs/unreleased/-23tvyuz.yml
- src/views/Pipeline.vue
Closes #
**Before :**
**After:**
> Wrapped title of the card and commented out unavailable description field(#23tvyuz)

- changelogs/unreleased/-23tw3xk.yml
- src/views/Pipeline.vue
> Displayed fallback string when no frequency found for a job on pipeline view(#23tw3xk)

- changelogs/unreleased/-23twj4e.yml
- src/views/Pipeline.vue
> Implemented alert before cancel job on pipeline page(#23twj4e)

- src/store/modules/job/JobState.ts
- src/store/modules/job/index.ts
> Removed unwanted code(#23twj34)

- src/views/Pipeline.vue
> Improved code to make segments on pipeline page responsive(#245drgx)

- src/components/JobDetail.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
> Implemented: support to pass recurrence time zone(#23ty1de)

- changelogs/unreleased/-245fq2j.yml
- src/store/modules/user/actions.ts
> Improved: action call to pass null and root property to clear jobs(#245fq2j)

- src/views/Pipeline.vue
> Implemented: pull to refresh feature of pipeline page

- changelogs/unreleased/-24b0y61.yml
- src/utils/index.ts
- src/views/InitialLoad.vue
> Implemented: code to update runTime and make the runTime button clickable(#24b0y61)

- changelogs/unreleased/-24b1qhb.yml
- src/components/JobDetail.vue
- src/locales/en.json
- src/store/modules/job/actions.ts
- src/views/Orders.vue
- src/views/Pipeline.vue
> Improved: code to display alert on success and failure and fetch the updated job information(#24b1qhb)

- src/store/modules/job/actions.ts
- src/store/modules/job/getters.ts
- src/store/modules/job/mutations.ts
- src/views/Pipeline.vue
> Displayed enum name instead of Job Name and Enum description on pipeline page(#24w5y8a)

- src/store/modules/job/getters.ts
> Fix: error of infinite scroll when there are no records(#24w686f)

- changelogs/unreleased/-257kfh8.yml
- src/views/Pipeline.vue
> Improved code to make items transparent on pipeline page(#257kfh8)

- changelogs/unreleased/-257p3jr.yml
- src/views/Pipeline.vue
> Fixed: the issue of time badge not displayed on the pipeline page(#257p3jr)

- changelogs/unreleased/-257p27w.yml
- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
> Improved: code to add support to show currentRetryCount on pending Job page (#257p27w).

- changelogs/unreleased/-25depf5.yml
- src/views/Pipeline.vue
> Removed full line from second last item of pipeline page cards(#25depf5)

- src/store/modules/job/actions.ts
- src/store/modules/user/actions.ts
> Improved: code to clear the job state on logout(#25k2nxy)

- changelogs/unreleased/-25k7kta.yml
- src/store/modules/job/actions.ts
> Fixed: a typo for runTimeData variable(#25k7kta)

- src/App.vue
- src/store/modules/user/actions.ts
Closes #
Currently, when the user login into the app and if the timezone is different an alert is shown. We have support to change the timezone from settings page. Remove the code to alert the user. 
**IMPORTANT NOTICE** - Remember to add a changelog entry
> Improved: code to remove timezone mismatch related alert on login (#2893rqm).

- src/views/Pipeline.vue
> Added copy action button on pipeline page pending job segment(#28med9h)

- src/views/Pipeline.vue
#107 
Closes #107 
Removed id and service name from pending job segment
> Removed id and service name from pending job segment(#28med88)

- src/components/Menu.vue
> Displayed shop information at the bottom of the menu(#28mf5yu)

- src/locales/en.json
- src/views/Pipeline.vue
> Implemented: functionality to add refresh button when we do not have jobs on pipeline page (#28940kn).

- src/App.vue
#126 
Closes #
Unregister the animation emitter in app.vue
> Improved: code to correctly unregister the animation emitter in the app.vue file(job-manager/#126)

- src/store/modules/user/actions.ts
> Removed unwanted action for clearing pending jobs(#2a23fur)

- src/components/JobConfiguration.vue
- src/locales/en.json
- src/views/InitialLoad.vue
> Removed: lastUpdatedStamp from jobConfiguration component and initialLoad page and Updated en.json file

- src/locales/en.json
- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
Added search functionality to search jobs by job description 
**Please Review**
Before
After
> Implemented support to search Job on Pipeline page(#2adk6nd)

- src/views/Pipeline.vue
Closes #
:- Improved code to add support to show history on running and history segments.
:- Improved code to handle the case of the missing slot of flex property.
> Improved: code to add support to copy and see job history on running and history segment (#2a7yjq9).

- src/views/Pipeline.vue
**Please Review**
Refactor: in pipeline page
- It improves code readability.
- Code reusable by calling getPendingJobs(),getRunningJobs(),getJobHistory();
> Improved: code to fetch jobs using predefined methods (#2adk6nd)

- src/views/Pipeline.vue
> Implemented code to show pinned jobs at the bottom of pipeline page(#295nvku)

- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
Filter jobs based upon pinned jobs (#2cqzpye)
Closes #
> Implemented: Filter jobs based upon pinned jobs(#2cqzpye)

- src/components/BatchModal.vue
- src/views/Orders.vue
Closes #
Added functionality to edit batch job
Fixed issue of date time not being updated
> Implemented: functionality to edit batch jobs and fixed issue of date time not being passed(#148)

- src/views/Pipeline.vue
Closes #
**Before:**
**After:**
> Improved code of pipeline page by placing search bar in header(#2cxrd4t)

- src/components/JobConfiguration.vue
- src/locales/en.json
> Updated and internationalized update job toast string(#2d92am7)

- src/components/JobConfiguration.vue
- src/locales/en.json
> Updated and internationalized cancel job and skip job toast strings(#2d92am7)

- src/components/InitialJobConfiguration.vue
- src/components/JobConfiguration.vue
- src/views/Orders.vue
> Improved code by showing routing item and labels clickable and added text wrapping to configuration component labels(#2d3dvzv)

- src/views/Pipeline.vue
> Improved code by updating background of pinned job title and icon (#2d92pdh)

- src/store/modules/job/actions.ts
- src/views/Orders.vue
#2d92ghd
Closes #
https://github.com/hotwax/job-manager/commit/6d55fb97c65abaef33dae2fefd34c9cb0dd9b7d1
Now user will easily be able to skip the job by swiping left to right and confirming to skip it.
https://user-images.githubusercontent.com/62360781/169819218-e3db7f51-be1c-47a0-b2bb-14685a05cd9d.mov
> Improved: BatchModal component with added - swipe left to right to skip the job functionality

- src/App.vue
- src/components/JobConfiguration.vue
- src/store/modules/user/actions.ts
- src/utils/index.ts
Closes #
Implemented logic to set the global timezone setting for the Luxon
Implmenented method to handle date time input and set it as per the user's selected timezone"
> Improved: honor user's selected timezone across the app (#2dewerv)

- src/components/BatchModal.vue
- src/components/InitialJobConfiguration.vue
> Improved: date time should honor user's selected timezone on Initial Job configuration and Batch modal (#2dewerv)

- src/store/modules/job/actions.ts
> Fixed: the issue of toast not being displayed when scheduling the job(#2deygbr)

- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
Fixed bug 
when filter is not applied based upon the pinned jobs job list is not fetched with condition systemJobEnumId is required
Closes #
> job list is not fetched till filter is not applied (#2cqzpye)

- src/utils/index.ts
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
Reverts hotwax/job-manager#193
> Revert "Improved: runTime set to start of the day for 'EVERYDAY' frequency else current time (#2ftb2vw)"

- src/components/JobHistoryModal.vue
- src/store/modules/job/actions.ts
> Fixed: Removed code which passes entityName for the calls done in findJobs API(#2np1py0)

- src/services/WebhookService.ts
- src/store/modules/webhook/actions.ts
Closes #
https://github.com/hotwax/job-manager/commit/5c03c11053f597aaf5391eb566cd0a186f6b8102
Now only a single service will be called for subscribe methods.
> Fixed: Code to use a single service to subscribe webhook(#2fz59a8)

- src/components/BatchModal.vue
- src/components/InitialJobConfiguration.vue
- src/components/JobConfiguration.vue
#2dmq8ja
Closes #
https://github.com/hotwax/job-manager/commit/17d74f7d7feda9994745022eadde815890037a27
Now time format will be more user friendly as it will be in 12 hours format
> Fixed: DateTime component has different hour cycle on different devices(#2dmq8ja)

- CONTRIBUTING.md
- README.md
> Updated contribution guideline point(#2r0kmb3)

- src/components/JobConfiguration.vue
- src/locales/en.json
> Implemented: functionality to have option to run jobs within 1 min(#2rhruw9)

- src/store/modules/job/actions.ts
> Improved: shop grp to be initially from 1 sequence and simlified query (#2te9p7v)

- src/locales/en.json
- src/store/modules/job/actions.ts
- src/views/Miscellaneous.vue
> Improved: Code to display message on miscellaneous page when no jobs found(#364ttxy)

- src/components/JobConfiguration.vue
Closes #
Implemented validation when the user set's runtime to accept only future date and time and show toast when an invalid, past date and time is given. Removed the use of minDateTime.
[Screencast from 13-09-22 06:47:00 PM IST.webm](https://user-images.githubusercontent.com/59442907/189911475-bb807612-89dc-46fa-8022-ad0b272fcd35.webm)
> Implemented: Validation to set only future date and time on setting runtime. (#2tzb5w4)

- src/store/modules/webhook/actions.ts
> Fixed: used console.error instead of console.log 

- src/components/BatchModal.vue
- src/components/InitialJobConfiguration.vue
- src/components/JobConfiguration.vue
- src/views/BulkEditor.vue
Closes #254 
- Adds confirmation buttons to all app date pickers
> Feature: Add confirmation buttons to date pickers

- src/components/InitialJobConfiguration.vue
- src/components/JobConfiguration.vue
> Fixed build fail by removing 'show-default-buttons = true' error in InititalJobConfiguration and JobConfiguration (#2zb7dhk)

- .env.example
- src/views/Login.vue
> Added support to alias specific instance URL with environment configuration(#30dkjp1)

- src/components/MoreJobs.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
> Fixed: Job runtime not set on jobConfiguration page in case of moreJobs(#2vjxdha)

- package-lock.json
- package.json
> Preparing for release 1.3.0

- src/components/JobConfiguration.vue
- src/store/modules/job/actions.ts
Reverts hotwax/job-manager#315
> Revert "Fixed: Jobs getting scheduled multiple times(#32qywdd)"

- src/components/JobConfiguration.vue
- src/store/modules/job/actions.ts
Reverts hotwax/job-manager#321
> Fixed: Jobs getting scheduled multiple times(#32qywdd)

- src/services/JobService.ts
- src/services/ProductService.ts
- src/services/UserService.ts
- src/services/UtilService.ts
> Implemented: Used HTTP get method for all the API calls to fetch data(#85zrh15tj)

- src/views/Orders.vue
Closes #
When sending a single property in `fieldList` then we get special charater in the response thus breaking the flow.
Added another property `productStoreId` in `fieldList` to ensure that we get a valid response.
> Fixed: issue of having a special character in response when sending a single property in fieldList array

- package-lock.json
- package.json
- release-notes.md
> Updated: app version  and release notes for minor release(v2.1.0)

- package-lock.json
- package.json
> Updated: app version for patch release

- package-lock.json
- package.json
> Updated: version for patch release (2.1.2)

- src/store/modules/job/actions.ts
> Fixed: Run now functionality not working for already runnning job (#423)

- package-lock.json
- package.json
> Updated: app version for patch release(v2.1.3)

- package-lock.json
- package.json
> Updated: app version for minor release (2.2.3)

- src/services/UserService.ts
> Fixed: wrong base user when getting shopify config for product store change

- package-lock.json
- package.json
- release-notes.md
> Improved: app version and release notes for patch release(v2.2.2)

- package-lock.json
- package.json
> Updated: app version for minor release (2.4.0)

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for minor release(v2.5.0)

- package-lock.json
- package.json
> Updated: app version for minor release (2.5.0)

- release-notes.md
> Updated: release notes for the release v2.6.0

- src/components/InitialJobConfiguration.vue
- src/store/modules/job/actions.ts
> Fixed: issue with scheduling initial load order job

- package-lock.json
- package.json
> Updated: app version for patch release (2.6.1)

- src/components/JobActionsPopover.vue
- src/components/JobConfiguration.vue
- src/components/JobConfigurationForBulkScheduler.vue
- src/components/JobHistoryModal.vue
- src/components/MoreJobs.vue
- src/store/modules/job/actions.ts
- src/store/modules/job/getters.ts
- src/views/JobDetails.vue
- src/views/Pipeline.vue
- src/views/SelectJobsModal.vue
Used enumName from job data instead of making another api call to fetch enumName
Applied same for the description
Closes #487 
Closes #489 
> Fixed: Enum name should appear on the job card and job list (#487)

- src/services/UserService.ts
> Fixed: build error TS2532: Object is possibly 'undefined'.

- package-lock.json
- package.json
- release-notes.md
> Updated: app version and release notes for patch release(v2.8.1)

- package-lock.json
- package.json
- release-notes.md
> Updated: app version for minor release (2.9.0)

- src/views/Miscellaneous.vue
Closes #459 
- Increased the viewSize to 100
- Defined logic to display single instance of a job when the job is in pending and draft status
Before:
After:
> Fixed: infinite scrolling not working on misc page(#459)

- src/router/index.ts
> Removed routing guard from login

- src/locales/en.json
- src/router/index.ts
- src/user-utils/index.ts
- src/views/Settings.vue
> Implemented: routing to launchpad login on logout

- src/views/Inventory.vue
> Fixed: logic missing to get the updated webhook info on inventory page load

- package-lock.json
- package.json
> Updated: DXP entry in package.json and package.lock

- src/router/index.ts
- src/store/modules/user/actions.ts
> Implemented: plugin state reset on logout

- src/store/modules/job/actions.ts
> Fixed: shopifyConfigId not being passed when running/scheduling a job frequently(#570)

- src/components/JobActionsPopover.vue
- src/components/JobConfiguration.vue
- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
> Improved: Include Run-Time Data in Copied Job Information (#576)

- package-lock.json
- package.json
> Updated: package and lock file for release(v2.10.0)

- src/components/JobActionsPopover.vue
- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
- src/views/Reports.vue
> Fixed: draft jobs not fetched on misc and reports page

- src/components/Filters.vue
> Implemented: support for reports filter on pipeline page(#582)

- package-lock.json
- package.json
> Updated: package-lock and package file for minor release(v2.11.0)

- package-lock.json
- package.json
- src/router/index.ts
> Fixed: Invalid navigation guard & upgraded dxp component to 1.3.3

- package-lock.json
- package.json
- src/locales/en.json
- src/main.ts
- src/router/index.ts
- src/user-utils/index.ts
- src/views/Settings.vue
> Implemented: button for navigating to launchpad and handled launchpad and app logout

- src/locales/en.json
- src/store/modules/job/actions.ts
- src/views/Pipeline.vue
> Improved: Displayed running duration for jobs on the Running Page.

- package-lock.json
- package.json
> Updated: app version for minor release (2.12.0)

- package-lock.json
- package.json
> Updated: app version for minor release (2.13.0)

- package-lock.json
- package.json
> Updated: package.json and package-lock.json for minor release 2.14.0

- src/store/modules/job/actions.ts
- src/views/Brokering.vue
- src/views/Fulfillment.vue
- src/views/InitialLoad.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
> Improved: job fetching query when clicking on job from list to open job configuration(#619)

- src/views/Brokering.vue
> Fixed: imports missing for toast and translation

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v2.15.0)

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v2.15.1)

- package-lock.json
- package.json
- src/components/Menu.vue
Closes #
- Used menu footer navigation component from DXP
- Added support to check for browser and user timezone
After:
> Implemented: menu navigation support using dxp component

- package-lock.json
- package.json
Closes #
Updated: App version for minor release (2.16.0).
> Updated: App version for minor release (2.16.0).

- src/utils/index.ts
> Fixed: object parsing issue when displaying additional params on UI and scheduling the service

- package-lock.json
- package.json
Closes #
Updated: App version for the fix release (2.16.1).
> Updated: App version for the fix release (2.16.1).

- src/utils/index.ts
Closes #
Fixed: Coverted to String before applying trim function in order to handle numeric values.
> Fixed: Converted to String before applying trim function in order to handle numeric values.

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (2.17.0).
> Updated: app version for the minor release (2.17.0).

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release (v2.18.0).
> Updated: app version for the minor release (v2.18.0).

- src/views/Fulfillment.vue
Closes #
Fixed: label for the notification job on fulfillment page.
> Fixed: label for the notification job on fulfillment page.

- package-lock.json
- package.json
Closes #
Updated: app version for the minor release v2.19.0
> Updated: app version for the minor release v2.19.0

- src/store/modules/user/actions.ts
> Fixed: Permission issue when defining a base permission for app

- src/components/JobHistoryModal.vue
> Improved: History Button Displaying filtered Jobs Across All Shopify Configs(#661)

- src/store/modules/user/actions.ts
> Added: Support to Remove Duplicate Permission Ids passed in the API request.

- package-lock.json
- package.json
> Updated: app version for minor release (v2.20.0)

- src/components/JobHistoryModal.vue
> Fixed: typo in the getter that was fetching the config name due to which the history is not visible for some jobs(#674)

- package-lock.json
- package.json
> Updated: app version in package and lock file for patch release(v2.20.1)

- package-lock.json
- package.json
> Updated: app version in package and lock file for minor release(v2.21.0)

- package-lock.json
- package.json
Closes #
Updated: app version for minor release (v2.21.0).
> Updated: app version for minor release (v2.22.0).

- package-lock.json
- src/components/BatchModal.vue
- src/components/JobParameterModal.vue
#698 
- Only displaying a single line for custom params and remove the duplicate line.
- Removed the copy icon from the modal when there is no data to copy inside the custom params modal
> Fixed: Extra line when displaying helper/error text and remove copy icon (#698)

- src/main.ts
Related Issue #691
Added a entry in main file to fix html tags not working in the translations.
Before 
After
> Fixed: html tags not working in the translations (#691)

- src/components/JobParameterModal.vue
Related Issue #678
Fixed item lines inconsistency issue in job-manager app.
Before
After
> Fixed: inconsistencies in line display on custom parameters modal (#678)

- package-lock.json
- package.json
Closes #
Updated: app version for the patch release (v2.23.1).
> Updated: app version for the patch release (v2.23.1).

- package-lock.json
- package.json
#
Updated: app version for patch release (v2.23.2).
> Updated: app version for patch release (v2.23.2).

- package-lock.json
- package.json
> Updated: app version for the minor release v2.24.0

- src/components/JobConfiguration.vue
> Removed: logic to disable the pin job action for history job config

- package-lock.json
- package.json
> Updated: app version for the minor release v2.25.0.

- package-lock.json
- package.json
> Updated: app version for minor release v2.26.0

- src/store/modules/maargJob/actions.ts
#734
Fixed maarg job enum description not showing up while first time fetching of the maargjobs
> Fixed: maarg job enum description not showing up while first time fetching of the maargjobs (#734)

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.26.1)

- src/components/ScheduleModal.vue
- src/views/PreOrder.vue
#
Having duplicate aside tags resulting in the issue
> Fixed: issue of configuration component not being visible and UI being distorted on the preorder page

- src/views/Fulfillment.vue
- src/views/InitialLoad.vue
- src/views/Inventory.vue
- src/views/Miscellaneous.vue
- src/views/Orders.vue
- src/views/Pipeline.vue
- src/views/PreOrder.vue
- src/views/Product.vue
- src/views/Reports.vue
#737
Improved code to close the maarg jobs detail card on changing the product store same as for other jobs.
> Improved: closing job details of maarg jobs on product store change #737)

- package-lock.json
- package.json
- src/components/LearnMoreModal.vue
#773
- Added support to handle the AI-generated Markdown response as an answer to job-related queries.
- Additionally, integrated `vue-markdown-render` to parse the Markdown.
> Fixed: Added support to handle the Ask API's Markdown response (#773)

- src/views/InitialLoad.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/Product.vue
#786 
Removed the UI for displaying webhooks(commented out the code), not removed any other related logic as we will be adding the support once the backend schema is updated
> Removed: webhook support from the app(#786)

- src/components/MaargJobConfiguration.vue
- src/services/MaargJobService.ts
- src/store/modules/maargJob/actions.ts
- src/views/Fulfillment.vue
- src/views/Inventory.vue
- src/views/Miscellaneous.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
#781
Added support to schedule job by cloning job from template job.
> Implemented: support for cloning job from the template job (#781)

- src/store/modules/maargJob/getters.ts
- src/views/Fulfillment.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
Related Issues
#783
Support to show moqui jobs instead of ofbiz one if migrated job exists else as backward compatability show ofbiz one.
> Implemented: support for showing moqui job instead of ofbiz if maarg job exists with backward compatability (#783)

- package-lock.json
- package.json
> Updated: app version for the minor release (v2.27.0)

- src/components/MaargJobConfiguration.vue
#790
Updated the job permission to be check for enable button.
> Fixed: entry of job permission for enable button (#790)

- package-lock.json
- package.json
> Updated: app version for the patch release (v2.27.1)

- src/store/modules/job/actions.ts
> Fixed: simplified logic for storing pending jobs in state by removing unnecessary conditions. (#754)

- src/locales/en.json
- src/views/Fulfillment.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
#822
Displayed seperate card and entries for the netsuite job other than in feed card.
> Improved: shown seperate card for the netsuite jobs (#822)

- package-lock.json
- package.json
> Updated: app version for minor release v2.28.0

- src/locales/en.json
- src/views/Fulfillment.vue
- src/views/Inventory.vue
- src/views/Orders.vue
- src/views/PreOrder.vue
- src/views/Product.vue
#822
Updated the label of netsuite job from "Netsuite" to "NetSuite"
> Improved: Netsuite card label spelling (#822)

- package-lock.json
- package.json
> Updated: app version for patch release v2.28.1

- package-lock.json
- package.json
> Improved: app version in package and lock file for patch release(v2.29.1)

- package-lock.json
- package.json
> Improved: app version in package and lock file for minor release(v2.30.0)
