changelogs/unreleased/-24pf5z2.yml
src/components/JobDetail.vue
src/views/Orders.vue
src/views/Pipeline.vue

When cancelling a job the job again gets scheduled as it's missing the cancelDateTime
Closes #
Passes cancelDateTime when cancelling a job

Improved: code to pass cancelDateTime when canceling a job(#24pf5z2)

---

src/components/Menu.vue

#116 
Closes #116 
Currently whole eCom store data was getting displayed. But we have now specified that we only want to display store name from eCom store
**Before:**
**After:**

Improved code by displaying only store name in place of whole eCom store data(#28zrvv1)

---

src/locales/en.json
src/store/modules/job/actions.ts

Closes #119 
Improved code so that user can not schedule job without selecting product store, if he is trying to schedule the job showed a toast `Please select product store before scheduling the job` on screen.

Improved: code so that user should not be able to schedule job without selecting product store (#28zthxn).

---

src/components/JobHistoryModal.vue
src/store/modules/job/actions.ts
src/views/Pipeline.vue

Closes #
Updated date time format in job history modal and history segment.
Displayed cancel/finish time instead of run time in history segment.
Made status description dynamic in running segment.
Updated the action for fetching running jobs

Updated DateTime code for job history modal and history segment(#2894bh1)

---

src/store/modules/job/actions.ts

Closes #
Worked on fixing the code to handle the case when the status property is not present on the job. Added status property on incoming jobs so that we can update the job from the pipeline page.
https://user-images.githubusercontent.com/52008359/166918333-412e6f8c-a0d4-4aaa-819d-f38e49d83548.mp4

Fixed: code to handle the case on pipeline page when saving the job (#29wed7c).

---

src/views/Pipeline.vue

Closes #
Implemented functionality to add support to copy and see job information on the history on running and history segment.

Improved: code to add support to copy and see job information on history and running segment (#2a7yjq9).

---

src/views/TimezoneModal.vue

Closes #
:- Worked on improving the code to use keyUp event for enter button instead of 'ionInput' for timeZone search.

Improved: code to use enter instead of input for Timezone search (#2cj8zmd).

---

src/store/modules/user/actions.ts

Closes #
:- Worked on improving the code to move 'None' option at bottom of the product stores list and select the first product store by default in all cases.
**Reason :** Right now when a user logs into the app "None" product store is selected by default. This option is not relevant in most cases anymore but we want to keep it around incase there are jobs we need to manage that are not associated with a specific product store.
https://user-images.githubusercontent.com/52008359/168738342-8ab6aaf4-37a1-49ac-9edf-3d23a241ace9.mp4

Improved: code to add 'None' option at bottom of product stores list and select first productStore by default (#2cjevda).

---

src/locales/en.json
src/views/PreOrder.vue

Closes #
:- Fixed typo on releasing job description and updated key in `en.json` file.
**Reason :** We have updated the value of releasing-job-description on the en.json file but did not updated its key now it is fixed in this PR.
https://user-images.githubusercontent.com/52008359/168749319-b530bd66-8d13-4285-a07f-f24e1fd7fc0f.mp4

Fixed: typo in releasing job description (#2cqxucv).

---

src/components/JobConfiguration.vue
src/store/modules/job/actions.ts
src/store/modules/job/getters.ts
src/store/modules/user/actions.ts
src/views/PreOrder.vue
src/views/Settings.vue

Closes #133 
:- Worked on reverting unused import of DateTime emitter from user module.
:- Worked on reverting unused context variables from actions related to the user module.
:- Worked on reverting unused code to revert unused variable from actions.ts of job module.
:- Worked on reverting unused code to revert unused import statement from the 'JobConfiguration' component.
:- Worked on reverting unused code to revert unused import statements to resolve errors from the app.
**Reason:** We are getting these warnings because we have imported some files and dependencies and defined some variables which are not used anywhere so that's why removed them to resolve these warnings.
https://user-images.githubusercontent.com/52008359/168806308-abb14a7c-dbbc-4afa-ad3b-be0655cd9bd2.mp4
**IMPORTANT …

Fixed: console warnings of import and undefined (#257v6ck).

---

src/store/modules/user/actions.ts

Closes #
When the user logins, as the product stores are not yet available it is sent empty, and wrong job list is fetched. Users should be logged in only after current product store is set
https://user-images.githubusercontent.com/44576058/169495573-a1d41b47-5c7b-4211-8185-65a78764c76a.mp4

Fixed: Pending jobs of Pipeline page are not updated on login(#2cxv1xh)

---

src/views/TimezoneModal.vue

Closes #
:- Worked on improving the code to assign input field to instance variable for searchbar.
Because when performing any action on search with enter key, the value of instance variable is set after the action is performed due to which wrong data is passed to API.

Improved: code to assign input field to instance variable for searchbar (#2cj8nc4).

---

src/components/BatchModal.vue

#2d99ucd
Closes #
https://github.com/hotwax/job-manager/commit/a8598746dc8b744d87af39d22d21a2f0eda176b2
Now user can see correct information of scheduled job.
https://user-images.githubusercontent.com/62360781/170114112-5eb9d71b-2888-45b2-a22f-dd10d4fc7381.mov

Fixed: Show the correct job information when clicking on an already scheduled batch job(#2d99ucd)

---

src/components/JobConfiguration.vue
src/store/modules/job/actions.ts

Closes #
No information being displayed when job is scheduled successfully

Fixed: issue of toast not being displayed when scheduling a job using toggle, checkbox or a new batch job(#2deygbr)

---

src/views/Pipeline.vue

Closes #
Before:
JobConfiguration component present in DOM when coming back from any other page to pipeline page

Fixed: issue of configuration component taking space in DOM but data not being displayed when coming back to pipeline page

---

src/store/modules/job/actions.ts

When scheduling a job the temporal expression for the job is not being set
Closes #
Passed the field SERVICE_TEMP_EXPR when scheduling the job as this field overrides the already passed field tempExprId

Fixed: issue of temp expr not being set when scheduling a new job(#2dmgzqb)

---

src/store/modules/job/actions.ts

In Order to schedule a job, the Run as System for scheduled jobs is not being set
Closes #

Fixed: runAsUser not set to Job when scheduling a new Job(#2f2ex62)

---

src/views/Orders.vue

The button for auto cancel order daily is not checked even when the job is scheduled.
Closes #
The issue is due to the wrong enum being mapped to the toggle button, so added the correct enum mapping.

Fixed: issue of auto cancel job check is not reflected on UI when the job is scheduled(#28u4g5n)

---

src/store/modules/job/actions.ts

When scheduling a job, then in runtimeData we are getting some values as "null", and when passed it results in an error on the server.
Closes #
Added a check when scheduling a service to assign empty string to those properties in runtimeData whose value is "null".

Fixed: the issue of null value being passed in payload when scheduling a job(#2hjh89u)

---

src/utils/index.ts
src/views/Inventory.vue
src/views/Orders.vue
src/views/PreOrder.vue

Closes #
Implemented: update runtime method to set the start of the day & current time according to job frequency
If job frequency is 'EVERYDAY' it will set start of the day else current time

Improved: runTime set to start of the day for 'EVERYDAY' frequency else current time (#2ftb2vw)

---

src/store/modules/user/UserState.ts
src/store/modules/user/actions.ts
src/store/modules/user/getters.ts
src/store/modules/user/index.ts
src/store/modules/user/mutations.ts

Updated: code to fetch shopifyConfigId corresponding to product store(#2kbnqzb)

---

src/views/JobDetails.vue

#2deygnv
Closes #
https://github.com/hotwax/job-manager/commit/569e768ba134098c2bf7523ea18b88981a1c8bd6
(On mobile view) - Now when user navigates back even on refresh, He/She lands on correct page i.e page, He/She came from not the home page.
https://user-images.githubusercontent.com/62360781/170435712-d6fba750-f0cd-42de-9e19-125fed7e025a.mov
https://user-images.githubusercontent.com/62360781/170436365-0595a383-17d2-4259-9184-669b413b687c.mov

Fixed: After refreshing and then clicking the back button the user is  redirected to the pipeline page(job-manager(#2deygnv)

---

src/store/modules/job/actions.ts
src/store/modules/webhook/actions.ts

Closes #
Fixed: Orders are not imported with multiple Shopify configuration 
- When changing the product store or scheduling any job, by directly accessing the state (`this.state.user.shopifyConfig`) the updated Shopify config Id is not accessed.
Now the state will be accessed by rootGetters (`rootGetters['user/getShopifyConfigId']`)

Fixed: Orders are not imported with multiple shopify configuration(#2mky5yp)

---

src/locales/en.json
src/views/Settings.vue

Improved label to "eCom Store" on Settings page (#23tw4yf) 

---

src/views/Orders.vue

Closes #
Worked on fixing the code to close slider after performing skip functionality on jobs related to order page.
https://user-images.githubusercontent.com/52008359/171145348-7cb5ef6d-d56e-4396-9510-26164d9b3af3.mp4

Fixed: code to close sliding option for skip action when it completes (#2ebeqzf).

---

src/components/JobConfiguration.vue
src/store/modules/job/actions.ts

Implemented: Added enum description to job config component(#364trwn)

---

package-lock.json
package.json
src/api/index.ts
src/services/JobService.ts

Used paramsSerializer available with axios to serialize params and qs npm package (https://www.npmjs.com/package/qs) for stringifying the parameters.
When passing object to qs, bracket or dot notation is returned as output. Handled the case by stringify the object before passing to qs.stringify() method
Closes https://app.clickup.com/t/2a2ancm

Fixed: Issue passing list to performFind with GET method (#2a2ancm)

---

src/components/JobActionsPopover.vue
src/locales/en.json
src/store/modules/job/actions.ts

Closes #
https://user-images.githubusercontent.com/62360781/183361711-8cf25b54-0730-445d-89e1-4b595114a6d1.mov

Implemented: Feature to run scheduled job right away(#364ttgf)

---

src/store/modules/job/actions.ts

When using run now functionality on a pending job, then the runTime for the pending job gets passed to the run now job.
Closes #
Added a check to not pass runTime when the job is of pending status when using run now functionality.

Fixed: the issue of service time being passed when using run now functionality for pending jobs(#2r0jq44)

---

src/components/JobActionsPopover.vue
src/store/modules/job/actions.ts

While fetching the Job, runtimeDataId was missing in fieldList due which runtime data was never fetched
Additonal change:
Close popover when the action is complete
Closes #

Fixed: missing productStoreId and shopifyConfigId for Job while using runNow (#2r0jq44)

---

src/store/modules/user/actions.ts

Closes #
:- Worked on reverting the ```getEcomStores``` action and fetching all stores in getProfile action.
https://user-images.githubusercontent.com/52008359/169795221-a0f2e3ef-22aa-47ba-ab1f-b25e8c4e76b4.mp4

Fixed: code to get 'eComStores' in 'getProfile' action instead of calling 'getEcomStores' action (#257v6ck).

---

.env.example
src/api/index.ts
src/services/UserService.ts
src/store/modules/user/actions.ts
src/store/modules/user/getters.ts

Implemented: Code to check if user has permission to access the app(#2hr41aq)

---

src/components/JobConfiguration.vue

Implemented: Add additional job actions to job config component(#364tt29)

---

src/components/JobConfiguration.vue

Closes #
https://user-images.githubusercontent.com/33576503/182549825-25357758-5707-44f5-8fc6-4579e118a324.mp4

Implemented: additional job actions, to job config component (#364tt29)

---

src/store/modules/job/actions.ts

SERVICE_TIME is passed for the jobs that are fetched with infinite scroll
While concatenating the new jobs fetched with infinite scroll the response is passed instead of the jobs variable modified as per the app schema.
status field which is populated in jobs is missing in response, thus when calling run service now as the status is undefined service time is passed as is
Closes #

Fixed: Run now functionality for the job manager is not working correctly (#2rhqqf7)

---

src/components/JobConfiguration.vue
src/store/modules/job/actions.ts
src/views/Pipeline.vue

Handled case when freq type is not available in environment file. Set default freq type if doesn't exist .env
Additional fixes:
Missing description when navigating from pipeline to Job Configuration. description field missing in field list while fetching pending jobs
When updating the frequency it is not reflecting on Job Configuration component, current is updated but jobStatus is not updated. Used updated lifecycle hook to reintialise the value
When skip or cancel job is done for pending jobs, UI flicker occurs. Current is updated whenever skip/cancel action is performed. It should be done only when JobConfiguration component is open and current has some value. Added check to check current before fetching and updating the job.
Removed some redundant code
Closes …

Fixed: Not able to open job update section on Pipeline page for some jobs (#2rht6hk)

---

src/store/modules/job/actions.ts
src/store/modules/user/actions.ts

When fetching jobs on various pages, shopId condition should be part of query in order to manage jobs based upon different shopify configuration Improved the logic for fetch job action to fetch draft and pending jobs separately. Cleared the jobs on shopify config change
Removed unused action in user state
Closes #

Fixed: shop should be honored while fetching jobs (#2te9p7v)

---

src/components/Menu.vue
src/store/modules/user/actions.ts

Fixed: error in console due to empty shopify configuration on logout(#2tky1f3)

---

src/components/JobConfiguration.vue
src/store/modules/user/actions.ts
src/views/Settings.vue

Closes #
Refactored action setEcomStore and setShopifyConfig to accept ID as well as object, as initially the whole object was passed, posing unnecessary code. 

Refactored: setEcomStore and setShopifyConfig actions to accept ID. (#2tzh44d)

---

src/components/InitialJobConfiguration.vue
src/components/JobConfiguration.vue

Closes https://github.com/hotwax/job-manager/issues/266
When setting jobs runtime initially or updating runtime for the existing job, the runtime is set to current time only. runtime should be set to user input value.

Fixed: runTime being set to current time while setting/updating time (#266)

---

src/views/Inventory.vue
src/views/Orders.vue
src/views/PreOrder.vue
src/views/Product.vue

Fixed: Title show in jobConfiguration component, earlier job title was not visible as title may come directly in jobInformation or jobInformation.job subObject
Closes #

Fixed: Title show in jobConfiguration component (#2vjxdha)

---

src/store/modules/user/actions.ts

Closes #
Jobs were not being fetched when the product store was changed rapidly from the menu footer. This was caused due to synchronous handling- on changing the store, the event to change the Shopify config is also fired. But due to synchronous handling, on rapid change, the Shopify config event gets run even before the store change event has finished, hence, the Shopify config was not being set, causing jobs to not render. This was handled by making the getShopifyConfigs action async using the 'await' keyword.

Fixed jobs not appearing after store change from Menu footer (#2a7ymj3)

---

src/components/Filters.vue

Issue is due to the wrong enumId being used for brokering jobs
Closes #319 
Updated the enumTypeId to `BROKER_SYS_JOB`

Fixed: the enumTypeId for bokering jobs(#85zrgnpuc)

---

package-lock.json
package.json
release-notes.md

Updated: version for minor release and updated release notes

---

package-lock.json
package.json
src/views/Settings.vue
vue.config.js

Implemented: Code to show app version & build information on Settings page(#85zrhn8w8)

---

src/services/JobService.ts
src/store/modules/job/actions.ts

Closes #335 
cancelScheduledJob API adds some more details to job required for future tracking
You need to pass only jobId to it
https://user-images.githubusercontent.com/62360781/210073663-e5f4130f-c74f-4c2d-8d03-d92b77f99fbb.mov

Implemented: Added cancelScheduledJob service to cancel job(#85zrh3hjv)

---

src/components/JobConfigurationForBulkScheduler.vue
src/store/modules/job/actions.ts
src/views/BulkEditor.vue

Closes #
Fixed the remove button not working in the bulk scheduler for removing separate jobs. 
Also, removed the description placeholder in the bulk schedule card.

Fixed remove button not working for removing separate jobs in bulk scheduler (#85zrjgnwd)

---

.env.example
package-lock.json
package.json
src/components/Image.vue
src/components/JobHistoryModal.vue
src/logger/index.ts
src/main.ts
src/store/modules/job/actions.ts
src/store/modules/product/actions.ts
src/store/modules/user/actions.ts
src/store/modules/util/actions.ts
src/store/modules/webhook/actions.ts
src/views/BulkEditor.vue
src/views/Orders.vue
src/views/SelectJobsModal.vue

Implemented logger using vue logger plugin(#21uxamh)

---

package-lock.json
package.json
release-notes.md

Updated: app version and release notes for major release

---

src/components/BatchModal.vue
src/store/modules/job/actions.ts
src/views/Orders.vue

Fixed code to skip batch jobs while fetching the order jobs Changed the order for the getting order and batch jobs. await fetching for order sys jobs Added alert for missing configuration
Closes https://github.com/hotwax/job-manager/issues/373

Fixed: Save button while creating a batch for broker order service does not work (#373)

---

src/services/WebhookService.ts

Removed: appending the baseUrl with endpoint when subscribing the webhook
Closes #394 

Fixed: issue of webhook not working after successful subscription(#85zrpqhmn)

---

src/store/modules/job/actions.ts

Run now jobs should be excluded when fetching the jobs for specific pages
Closes #424 

Fixed: Temporal expression for the new scheduled jobs does not appear properly  (#424)

---

src/components/InitialJobConfiguration.vue
src/store/modules/job/actions.ts

Initial load job performs bulk operation and preferred to be run as system user. If the user associated with job is disabled, or password changes, the job may not run
Additional change:
Removed fetch jobs action cal for runServiceNow as the jobs which reflects through this action must have temp expression. Thus run now has no effect on current jobs.
Closes #423 

Improved: user scheduleService action instead of runServiceNow (#423)

---

src/components/JobConfiguration.vue
src/store/modules/job/actions.ts
src/views/Miscellaneous.vue

Additional fix:
Jobs not updated from miscllaneous page after skip, cancel or update action
Closes #462 

Fixed: job information disappear after cancelling (#462)

---

src/store/modules/job/actions.ts

As per the current logic, when fetching the jobs the draft jobs doesn't replace existing pending job in cached. When getting individual job, removed the cached job and then updated the cached as received from server
Closes #

Fixed: jobs list not updated when cancelling a job from configuration

---

src/locales/en.json
src/store/modules/job/actions.ts

When scheduling a job, if the job runtime requires shopifyConfigId or shopId and it is missing in passed data, skip scheduling the job with a toast stating the reason
Closes #502 

Improved: Show toast if shopifyConfig required for the job is missing while scheduling (#502)

---

src/components/InitialJobConfiguration.vue
src/components/JobConfiguration.vue
src/store/modules/job/actions.ts

Fixed: 'now' option for run time not working (#517)

---

src/components/Menu.vue

Related issue: https://github.com/hotwax/dxp-components/issues/122
Fixed issue of menu not being enabled for the correct page when using the back button in Job Manager app.
- Removed a watcher from the menu component that checks for route changes
- Defined a computed property to find the correct index in the menu list

Implemented: Page Selection Persistence for Job Manager App with Side Navigation (#122)

---

src/components/JobParameterModal.vue
src/locales/en.json

Closes #605
Added an empty state text for jobs with no custom parameters in the orders page in the job-manager app.
Before
After

Improved: Added empty state text for jobs with no custom parameters (#605)

---

src/components/InitialJobConfiguration.vue
src/components/JobConfiguration.vue

Removed: spacing after param name when displaying the custom parameters for a job

---

src/views/Product.vue

Closes #
Resolved issue with moreJobs details not visible since passing length of jobs as props. Hence removed .length from the moreJobs props.

Fixed: moreJobs details not visible on Products page

---

src/store/modules/job/actions.ts
src/views/Brokering.vue
src/views/Fulfillment.vue
src/views/InitialLoad.vue
src/views/Inventory.vue
src/views/Orders.vue
src/views/Product.vue

Closes #619
When fetchJobs actions fails while rendering a page, clicking a job doesn't get job. Hence updated updateCurrentJob parameters so as to successfully fetch job info once already failed at the time of page rendering.

Improved: job fetching query when clicking on a job panel to open job configuration (#619)

---

src/store/modules/job/actions.ts

Fixed: case to empty the runTime epoch when updating a job or skipping a job

---

src/locales/en.json
src/utils/index.ts
src/views/FailedJobReasonModal.vue

Closes #
Implemented button for copying failed job reason from the modal.

Implemented: button for copying failed job reason in the modal

---

src/views/TimezoneModal.vue

Closes #
Spinner is added to show that the timezones are being fetched from the API. It is indicating to the user that the data is loading.

Implemented: Spinner in timezone modal so users can see that data is being fetched

---

src/services/UserService.ts

Related Issue #685
Improved the login logic such that whenver a user login with no shopify config associated we will not stop them and allow them to login.
- The jobs which uses shopifyConfigId for scheduling and running will not be displayed in the app when we don't have any associated shopifyConfig.

Improved: login code to allow user to login without shopifyShop association (#685)

---

src/views/Pipeline.vue
src/views/SelectJobsModal.vue

https://github.com/hotwax/dxp-components/issues/289
Removed the logic to re-render the infinite-scroll on queryString check that has been added in the previous PR.
Added a variable to check whether the scrolling can be enabled or not whenever users lands on the list page. For this, we have determined the height of the content part scroll and infiniteScroll component and if the height is less than 0 then only enabling the infinite-scroll component
Removed disabled as once the infiniteScroll is disabled it does not gets enabled again, hence removed the disabled property and instead used v-show to enable/disable infinite scroll.

Fixed: infinite scroll issue when used with searchbar(dxp-289) 

---

src/store/modules/user/actions.ts
src/store/modules/webhook/actions.ts

#702 
- Modify `setCurrentShopifyConfig()` to ensure that the `shopifyConfig` object includes the `shopId` and `name`
- Update the `fetchShopifyWebhooks` service to handle cases where no webhook is subscribed for a specific `shopifyConfig`.

Fixed: changing the shopifyConfig now update the webhook(#700)

---

src/components/CustomFrequencyModal.vue

#714 
- Ensured that the ion-radio and ion-label elements are placed within the ion-item element.
- The ion-radio element is positioned before the ion-label element and assigned the slot="start" attribute to place it at the start of the ion-item.

Fixed: positioning of the ion-radio items label and the circleOutline(#714)

---

src/views/Pipeline.vue

#
For the job where data manager logs are present then in that case, the animation for job configuration is having a flicker effect.

Fixed: issue in animation when fetching data manager log for the job(#680)

---

src/views/Pipeline.vue

#742 
- Implemented a single elevated card state to highlight one job card at a time by conditionally applying CSS.

Improved: Added CSS to highlight the selected job card(#742)

---

firebase.json

#735 [#104](https://github.com/hotwax/launchpad/issues/104)
this code works for deploying and hosting SPAs built with
frontend frameworks on Firebase Hosting, while handling
multiple environments and including essential security headers in development.

Improved firebase configuration by adding security headers(#735)

---

src/store/modules/maargJob/actions.ts
src/views/Fulfillment.vue
src/views/InitialLoad.vue
src/views/Inventory.vue
src/views/JobDetails.vue
src/views/Miscellaneous.vue
src/views/Orders.vue
src/views/Pipeline.vue
src/views/PreOrder.vue

#734
- Implemented the support for showing the maarg job in the mobile view
- Also clearing the state for currentMaargJob on tab change.

Implemented: mobile view for the maarg jobs (#734)

---

src/components/LearnMoreModal.vue

#726 
- If a summary is not present for a job, an empty state will appear on the modal.
- If sources are not present for any reason, the summary may still be visible on the modal.

Improved: Added checks for various cases on the "Learn More" modal(#726)

---

src/views/Pipeline.vue

#762 
- The main element's top margin is removed, its height is set to 100%, and vertical overflow is hidden. Because of this, the main element now takes up the full height of the page.  
- The section and aside elements are allowed to scroll independently, their scrollbars are hidden, and padding is added to their top.  
- Since scrolling is now moved to the section, a scroll event and the `enableScrolling` function have been added to it. These help toggle the `isScrollingEnabled` flag to control whether infinite scrolling can be triggered.  
- Additionally, the class `ion-content-scroll-host` has been added to the section to let `ion-infinite-scroll` recognize the scrolling element.  
- Also updated the space variable for the job cards' margin-block.

Implemented: Independent scrolling behavior for the job list section and the job config aside elements(#762)

---

src/components/JobConfiguration.vue
src/views/DataManagerLogDetails.vue

#761 
- For now, removed the ion-icon from the ion-chip as the ripple effect was behaving inconsistently when conditionally adding the ion-icon inside the ion-chip.
- Used the outline property to indicate the selected logs filter.
- Improved the styling of the Import Logs Details page.

Improved: Fixed the ion-chip ripple effect and updated the import logs details page styling(#761)

---

src/components/MaargJobConfiguration.vue

#793
Fixed the issue related to Product store id not setting in job param on cloning the job.

Fixed: productStoreId not setting in job param on cloning the job (#793)

---

src/views/PreOrder.vue

#807
Fix incorrect detaching of method from the emitter on disabling in Pre-order page.

Fixed: wrong method detaching from emitter form Pre-order page (#807)

---

src/components/JobHistoryModal.vue
src/components/MaargJobConfiguration.vue
src/store/modules/maargJob/actions.ts
src/views/Fulfillment.vue
src/views/Inventory.vue
src/views/Miscellaneous.vue
src/views/Orders.vue
src/views/PreOrder.vue
src/views/Product.vue

#816
Showing enum name instead of showing enum description in moqui jobs.

Improved: showing enumName instead of enumDescription in moqui jobs (#816)

---

src/components/Filters.vue

#827 
- Removed the 'Reports' option from the job category filter on the Pipeline page.

Improved: Removed the 'Reports' option from the job category filter (#827)

---

src/store/modules/job/actions.ts

#829 
- Fixed issue related to job scheduling due to missing field `instanceOfProductId` in the `JobSandbox` entity.

Fixed issue related to job scheduling (#829)

---

src/locales/en.json
src/views/Settings.vue

#784 
- Added a fallback text in case when no shopify shop is associated with the product store .
updated UI

Fixed : The Select E-Commerce Store option remains visible even when no shopify shop is associated with the product store.(#784)
